# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
# Exercise 1
import numpy as np

array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [3]:
# Exercise 2
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [5]:
# Exercise 3
import numpy as np

evenly_spaced = np.linspace(0, 5, 10)
print(evenly_spaced)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [7]:
# Exercise 4
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [9]:
# Exercise 5
import numpy as np

random_matrix = np.random.rand(4, 4)
print(random_matrix)

[[0.25459042 0.84406289 0.10468868 0.95207396]
 [0.93424771 0.09339811 0.94719865 0.7145747 ]
 [0.10147312 0.93574975 0.12555292 0.89543624]
 [0.69932279 0.29495349 0.86494193 0.75785413]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [11]:
# Exercise 6
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [13]:
# Exercise 7
import numpy as np

# Create a 1D array with 16 elements
array_1d = np.arange(16)

# Reshape to 4x4
array_2d = array_1d.reshape((4, 4))

print(array_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [15]:
# Exercise 8
import numpy as np

array = np.array([1, 2, 3, 4])
print(array.dtype)

int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [17]:
# Exercise 9
import numpy as np

# Create array from 1 to 100
array = np.arange(1, 101)

# Filter even numbers
even_numbers = array[array % 2 == 0]

print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [19]:
# Exercise 10
import numpy as np

random_matrix = np.random.randint(10, 51, size=(6, 6))
print(random_matrix)

[[33 21 48 28 15 30]
 [28 34 44 12 49 49]
 [12 38 20 19 27 22]
 [27 22 22 18 45 23]
 [25 21 10 48 27 36]
 [37 10 37 41 20 12]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [21]:
# Exercise 11
import numpy as np

# Create a 5x5 array for demonstration
array = np.arange(1, 26).reshape(5, 5)
print("Original array:\n", array)

# Extract a 3x3 submatrix from rows 1 to 3 and columns 2 to 4 (0-based indexing)
submatrix = array[1:4, 2:5]
print("\nSubmatrix:\n", submatrix)

Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Submatrix:
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [23]:
# Exercise 12
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = array.sum()
print(total_sum)

21



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [25]:
# Exercise 13
import numpy as np

array = np.array([1, 3, 5, 7, 9])

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 5.0
Median: 5.0
Standard Deviation: 2.8284271247461903



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [27]:
# Exercise 14
import numpy as np

array = np.array([10, 5, 8, 20, 3])

max_value = np.max(array)  # or array.max()
min_value = np.min(array)  # or array.min()

print("Maximum value:", max_value)
print("Minimum value:", min_value)

Maximum value: 20
Minimum value: 3



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [29]:
# Exercise 15
import numpy as np

# Create an array of 20 random integers between 0 and 100
array = np.random.randint(0, 101, size=20)

print("Array:", array)

# Find the index of the maximum value
max_index = np.argmax(array)
print("Index of maximum value:", max_index)
print("Maximum value:", array[max_index])

Array: [23 22 31 85 85 30 63 74 26 18  5 52 78 42 19 49 52 74 50 41]
Index of maximum value: 3
Maximum value: 85



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [31]:
# Exercise 16
import numpy as np

# Create a sample array
array = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_array = array[::-1]

print("Original array:", array)
print("Reversed array:", reversed_array)

Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [33]:
# Exercise 17
import numpy as np

# Create two 3x3 matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Element-wise multiplication
result = matrix1 * matrix2
# Alternatively: result = np.multiply(matrix1, matrix2)

print(result)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [35]:
# Exercise 18
import numpy as np

# Given 1D array
arr = np.array([1, 2, 3, 4])

# Create diagonal matrix
diag_matrix = np.diag(arr)

print(diag_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [37]:
# Exercise 19
import numpy as np

# Define two 2D arrays (matrices)
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication
result = A @ B
# Alternatively: result = np.dot(A, B)
# Or: result = np.matmul(A, B)

print(result)

[[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [39]:
# Exercise 20
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flatten to 1D using flatten()
flat_array = array_2d.flatten()
print("Flattened array (flatten):", flat_array)

# Flatten to 1D using ravel()
flat_array_ravel = array_2d.ravel()
print("Flattened array (ravel):", flat_array_ravel)

Flattened array (flatten): [1 2 3 4 5 6]
Flattened array (ravel): [1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [41]:
# Exercise 21
import numpy as np

# Two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically
result = np.vstack((a, b))

print(result)


[[1 2 3]
 [4 5 6]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [43]:
# Exercise 22
import numpy as np
# Define two arrays with the same neven_numbers
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

# Horizontal stacking 
result= np.hstack((a,b))
print(result)


[[1 2 5 6]
 [3 4 7 8]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [45]:
# Exercise 23
import numpy as np
a= np.array([1,2,3,4,5,6])
sub_arrays= np.split(a,3) # split into 3 equal parts 
print(sub_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [47]:
# Exercise 24
import numpy as np
# Generate a 3x3 array of random floats in [0,1) 
a= np.random.rand(3,3)

# Round to 2 decimal places 
rounded_a= np.round(a,2)

print("Original array:\n",a)
print("Rounded array:\n",rounded_a)

Original array:
 [[0.98311647 0.31265575 0.66671218]
 [0.90994415 0.70065838 0.25248478]
 [0.49533337 0.51548317 0.96613598]]
Rounded array:
 [[0.98 0.31 0.67]
 [0.91 0.7  0.25]
 [0.5  0.52 0.97]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [49]:
# Exercise 25
import numpy as np 
a= np.array([1,2,3,2,4,1,5])
unique_elements= np.unique(a) 
print("Unique elements:",unique_elements)

Unique elements: [1 2 3 4 5]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [51]:
# Exercise 26
import numpy as np 
a= np.array([[3,7,1],[8,2,9]])

# Replace values less than 5 with 5 
a[a<5]=5
print(a)

[[5 7 5]
 [8 5 9]]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [53]:
# Exercise 27
import numpy as np
a= np.array([1,2,3,4])
cumulative_sum= np.cumsum(a) 
print(cumulative_sum)

[ 1  3  6 10]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [55]:
# Exercise 28
import numpy as np

# create a sample array 
a= np.array([[0,1,2],[3,0,0],[4,5,0]]) 

# count non_zero elements 
non_zero_count= np.count_nonzero(a)
print("Number of non-zero elements:",non_zero_count)

Number of non-zero elements: 5



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [57]:
# Exercise 29
import numpy as np 
# create a 1D array of 10 random integers between 0 and 100 
a= np.random.randint(0,100, size=10) 

# sort the array in ascending order 
sorted_a= np.sort(a) 

print("Orgininal array:",a)
print("Sorted array: ",sorted_a)

Orgininal array: [ 2 73  3 71 83 59 11 12 86 92]
Sorted array:  [ 2  3 11 12 59 71 73 83 86 92]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [59]:
# Exercise 30
import numpy as np 
# create a 3x3 mmatrix 
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

# row-wise sum (sum across columns, axis=1)
row_sum= np.sum(a,axis=1)

# column-wise sum(sum across rows, axis=0)
col_sum= np.sum(a,axis=0)

print("Matrix:\n",a)
print("Row-wise sum:\n",row_sum)
print("Column-wise sum:\n",col_sum)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row-wise sum:
 [ 6 15 24]
Column-wise sum:
 [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [63]:
# Exercise 31
import numpy as np
# generate a 2D array of random values  
a= np.random.rand(3,4)*100 # values between 0 and 100

# normalize the array to range[0,1] 
normalized_a= (a-np.min(a))/ (np.max(a))
print("Orginal array:\n",a) 
print("\nNormalized array:\n",normalized_a)

Orginal array:
 [[78.83302675 50.21907296 30.00055352  5.1786626 ]
 [39.78494163 73.8301211  89.98449494 85.66143605]
 [91.93337941 21.18952403 98.01287927 10.04672793]]

Normalized array:
 [[0.75147638 0.45953563 0.25325132 0.        ]
 [0.35307889 0.70043303 0.86525192 0.82114487]
 [0.88513589 0.16335467 0.94716345 0.04966761]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [ ]:
# Exercise 32
import numpy as np 
a= np.array([1,2,3])
b= np.array([4,5,6])

# find the dot product 
dot_product= np.dot(a,b) 
print("Dot product:",dot_product)


---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [65]:
# Exercise 33
import numpy as np 
# create a 3x3 square matrix 
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
trace_val= np.trace(a) 

print("Matrix:\n",a)
print("Trace of the matrix:",trace_val)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of the matrix: 15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [69]:
# Exercise 34
import numpy as np 
# create a 2D array 
a= np.array([[1,2,3],[4,5,6],[7,8,9]]) 

# swap row 0 and row 2 
a[[0,2]]= a[[2,0]]
print("Array after swapping rows 0 and 2:\n ",a)

Array after swapping rows 0 and 2:
  [[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [73]:
# Exercise 35
import numpy as np 
# create a 1D array 
a= np.array([1,2,3,4,5])

# convert to column vector
column_vector= a.reshape(-1,1) 
print("Column vector:\n,", column_vector)

Column vector:
, [[1]
 [2]
 [3]
 [4]
 [5]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [82]:
# Exercise 36
import numpy as np 
# define a 3x3 matrix 
a= np.array([[1,2,3],[4,5,6],[7,8,9]]) 

# compute the determinant 
det= np.linalg.det(a)

print("Determinant:",det)

Determinant: -9.51619735392994e-16



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [84]:
# Exercise 37
import numpy as np

# Define a 2x2 matrix
matrix = np.array([[4, 2],
                   [1, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [86]:
# Exercise 38
import numpy as np

# Coefficient matrix
A = np.array([[2, 3],
              [3, 4]])

# Right-hand side
B = np.array([8, 11])

# Solve the system
X = np.linalg.solve(A, B)

print("Solution (x, y):", X)


Solution (x, y): [1. 2.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [88]:
# Exercise 39
import numpy as np

# Example original array
data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

# Parameters for Gaussian noise
mean = 0
std_dev = 0.1  # standard deviation of the noise

# Generate Gaussian noise
noise = np.random.normal(mean, std_dev, data.shape)

# Add the noise to the original data
noisy_data = data + noise

print("Original data:", data)
print("Noise:", noise)
print("Noisy data:", noisy_data)


Original data: [1. 2. 3. 4. 5.]
Noise: [-0.00333713  0.03568347  0.03176367 -0.00843199 -0.075958  ]
Noisy data: [0.99666287 2.03568347 3.03176367 3.99156801 4.924042  ]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [90]:
# Exercise 40
import numpy as np

# Create a 4x4 matrix
matrix = np.array([
    [10, 2, 3, 4],
    [5, 20, 7, 8],
    [9, 10, 30, 12],
    [13, 14, 15, 40]
])

# Extract the diagonal elements
diagonal = np.diag(matrix)

print("Matrix:\n", matrix)
print("Diagonal elements:", diagonal)


Matrix:
 [[10  2  3  4]
 [ 5 20  7  8]
 [ 9 10 30 12]
 [13 14 15 40]]
Diagonal elements: [10 20 30 40]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [92]:
# Exercise 41
import numpy as np

# Generate an array of 100 random values (e.g., from a normal distribution)
data = np.random.randn(100) * 20 + 30  # mean=30, std=20 (to get a wider range)

# Clip values to the range [10, 50]
clipped_data = np.clip(data, 10, 50)

print("Original data (first 10):", data[:10])
print("Clipped data (first 10):", clipped_data[:10])


Original data (first 10): [24.07144619 69.77302223 42.7585582  -9.8850192   0.8807057  22.88520471
 43.03245123 43.30318477 27.20196469  3.70039934]
Clipped data (first 10): [24.07144619 50.         42.7585582  10.         10.         22.88520471
 43.03245123 43.30318477 27.20196469 10.        ]



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [94]:
# Exercise 42
import numpy as np

# Create a 2D NumPy array with both positive and negative values
array = np.array([
    [5, -3, 7],
    [-1, 2, -6],
    [4, -2, 9]
])

# Replace all negative values with zero
array[array < 0] = 0

print("Modified array:\n", array)


Modified array:
 [[5 0 7]
 [0 2 0]
 [4 0 9]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [96]:
# Exercise 43
import numpy as np

# Define two 1D NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Inner product (dot product)
inner_product = np.inner(a, b)

# Outer product
outer_product = np.outer(a, b)

print("Array a:", a)
print("Array b:", b)
print("Inner product:", inner_product)
print("Outer product:\n", outer_product)


Array a: [1 2 3]
Array b: [4 5 6]
Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [98]:
# Exercise 44
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create a NumPy array of points (each row is a point)
points = np.array([
    [0, 0],
    [1, 0],
    [0, 1]
])

# Compute pairwise distances
distances = squareform(pdist(points))

print("Points:\n", points)
print("Pairwise distance matrix:\n", distances)


Points:
 [[0 0]
 [1 0]
 [0 1]]
Pairwise distance matrix:
 [[0.         1.         1.        ]
 [1.         0.         1.41421356]
 [1.         1.41421356 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [100]:
# Exercise 45
import numpy as np

# Define the data type with field names and data types
person_dtype = np.dtype([
    ('name', 'U20'),   # Unicode string of max length 20
    ('age', 'i4'),     # 32-bit integer
    ('height', 'f4')   # 32-bit float
])

# Create a structured array
people = np.array([
    ('Alice', 30, 5.5),
    ('Bob', 25, 6.0),
    ('Charlie', 35, 5.8)
], dtype=person_dtype)

# Accessing fields
print("All people:\n", people)
print("Names:", people['name'])
print("Ages:", people['age'])
print("Heights:", people['height'])


All people:
 [('Alice', 30, 5.5) ('Bob', 25, 6. ) ('Charlie', 35, 5.8)]
Names: ['Alice' 'Bob' 'Charlie']
Ages: [30 25 35]
Heights: [5.5 6.  5.8]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [102]:
# Exercise 46
import numpy as np

# Create a 5x5 matrix of random integers between 0 and 9
matrix = np.random.randint(0, 10, size=(5, 5))

# Count occurrences of each unique value
unique_values, counts = np.unique(matrix, return_counts=True)

# Combine into a dictionary (optional)
value_counts = dict(zip(unique_values, counts))

print("Matrix:\n", matrix)
print("Value counts:", value_counts)


Matrix:
 [[5 3 2 2 6]
 [7 6 6 7 2]
 [4 6 7 9 7]
 [5 9 7 4 4]
 [2 5 2 6 0]]
Value counts: {0: 1, 2: 5, 3: 1, 4: 3, 5: 3, 6: 5, 7: 5, 9: 2}



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [104]:
# Exercise 47
import numpy as np

# Generate a random 3x3 array (values between 0 and 1)
arr = np.random.rand(3, 3)

# Calculate the mean of each row (keepdims=True to allow broadcasting)
row_means = arr.mean(axis=1, keepdims=True)

# Subtract the row mean from each element in the row
result = arr - row_means

print("Original array:\n", arr)
print("Row means:\n", row_means)
print("Result after subtracting row means:\n", result)


Original array:
 [[0.95648247 0.96738237 0.16498224]
 [0.05939349 0.36214383 0.48851094]
 [0.62857185 0.77438962 0.06116692]]
Row means:
 [[0.69628236]
 [0.30334942]
 [0.4880428 ]]
Result after subtracting row means:
 [[ 0.26020011  0.27110001 -0.53130012]
 [-0.24395593  0.05879441  0.18516152]
 [ 0.14052906  0.28634682 -0.42687588]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [106]:
# Exercise 48
import numpy as np

# Create a random integer array, for example with values between 0 and 100
arr = np.random.randint(0, 100, size=20)

# Check if any value is greater than 50
any_greater_than_50 = np.any(arr > 50)

print("Array:", arr)
print("Any values greater than 50?", any_greater_than_50)


Array: [ 3 26 47 30 30 47 87  7 56 31 17 96 43 20 86 10 25 32 70 34]
Any values greater than 50? True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [108]:
# Exercise 49
import numpy as np

# Example 1D array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Window size
n = 3

# Create the window (equal weights summing to 1)
window = np.ones(n) / n

# Compute moving average using convolution, mode='valid' returns only positions with full overlap
moving_avg = np.convolve(data, window, mode='valid')

print("Original data:", data)
print(f"Moving average (window size {n}):", moving_avg)


Original data: [1 2 3 4 5 6 7 8 9]
Moving average (window size 3): [2. 3. 4. 5. 6. 7. 8.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [110]:
# Exercise 50
import numpy as np

# Two example 1D arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Calculate Pearson correlation coefficient matrix
corr_matrix = np.corrcoef(x, y)

# Extract the correlation coefficient between x and y
pearson_corr = corr_matrix[0, 1]

print("Pearson correlation coefficient:", pearson_corr)


Pearson correlation coefficient: 0.9999999999999999



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [112]:
# Exercise 51
import numpy as np

# Example array of radians
radians = np.array([0, np.pi/6, np.pi/4, np.pi/2, np.pi])

# Convert to degrees
degrees = np.degrees(radians)

print("Radians:", radians)
print("Degrees:", degrees)


Radians: [0.         0.52359878 0.78539816 1.57079633 3.14159265]
Degrees: [  0.  30.  45.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [114]:
# Exercise 52
import numpy as np

# Create a random array of size 10 (values between 0 and 1)
arr = np.random.rand(10)

# Compute variance
variance = np.var(arr)

# Compute standard deviation
std_dev = np.std(arr)

print("Array:", arr)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Array: [0.22017653 0.07950731 0.53699998 0.6549913  0.8230331  0.45299246
 0.90133477 0.4996368  0.29860926 0.16555788]
Variance: 0.06870654641071547
Standard Deviation: 0.2621193362015009



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [116]:
# Exercise 53
import numpy as np

# Create a 2D array
arr = np.array([
    [3, 5, 1],
    [7, 2, 9],
    [4, 6, 8]
])

# Indices of max values along each row (axis=1)
max_indices_rows = np.argmax(arr, axis=1)

# Indices of max values along each column (axis=0)
max_indices_cols = np.argmax(arr, axis=0)

print("Array:\n", arr)
print("Indices of max values in each row:", max_indices_rows)
print("Indices of max values in each column:", max_indices_cols)


Array:
 [[3 5 1]
 [7 2 9]
 [4 6 8]]
Indices of max values in each row: [1 2 2]
Indices of max values in each column: [1 2 1]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [118]:
# Exercise 54
import numpy as np

# Define a 2x2 matrix
matrix = np.array([[4, 7],
                   [2, 6]])

# Compute the inverse
inverse_matrix = np.linalg.inv(matrix)

print("Original matrix:\n", matrix)
print("Inverse matrix:\n", inverse_matrix)


Original matrix:
 [[4 7]
 [2 6]]
Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [120]:
# Exercise 55
import numpy as np

# Generate 10 random values
arr = np.random.rand(10)

# Standardize the array (mean 0, variance 1)
standardized_arr = (arr - arr.mean()) / arr.std()

print("Original array:", arr)
print("Standardized array:", standardized_arr)
print("Mean of standardized array:", standardized_arr.mean())
print("Std deviation of standardized array:", standardized_arr.std())


Original array: [0.63871535 0.08035161 0.46242032 0.8584234  0.34486156 0.96190101
 0.57537965 0.64674199 0.17824356 0.58343098]
Standardized array: [ 0.40243929 -1.7240952  -0.26898229  1.23919987 -0.71670612  1.63329548
  0.16122457  0.43300884 -1.35127261  0.19188816]
Mean of standardized array: 1.609823385706477e-16
Std deviation of standardized array: 0.9999999999999998



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [122]:
# Exercise 56
import numpy as np

# Define two arrays of the same shape
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise addition
add_result = a + b

# Element-wise subtraction
sub_result = a - b

print("Array a:", a)
print("Array b:", b)
print("Addition (a + b):", add_result)
print("Subtraction (a - b):", sub_result)


Array a: [1 2 3 4]
Array b: [5 6 7 8]
Addition (a + b): [ 6  8 10 12]
Subtraction (a - b): [-4 -4 -4 -4]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [124]:
# Exercise 57
import numpy as np

# Create an array of 10 random values
arr = np.random.rand(10)

# Find the index of the maximum element
max_index = np.argmax(arr)

print("Array:", arr)
print("Index of maximum element:", max_index)
print("Maximum element:", arr[max_index])

Array: [0.56690302 0.69968805 0.43133736 0.83494803 0.21561388 0.33219945
 0.23661465 0.36863688 0.31555214 0.57615   ]
Index of maximum element: 3
Maximum element: 0.8349480347249812



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [126]:
# Exercise 58
import numpy as np

# Create a 3x3 array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Rotate the array by 90 degrees counter-clockwise
rotated_arr = np.rot90(arr)

print("Original array:\n", arr)
print("Rotated array (90 degrees):\n", rotated_arr)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rotated array (90 degrees):
 [[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [128]:
# Exercise 59
import numpy as np

# Define a matrix
matrix = np.array([
    [1, 2],
    [3, 4]
])

# Compute Frobenius norm
fro_norm = np.linalg.norm(matrix, 'fro')

print("Matrix:\n", matrix)
print("Frobenius norm:", fro_norm)


Matrix:
 [[1 2]
 [3 4]]
Frobenius norm: 5.477225575051661



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [130]:
# Exercise 60
import numpy as np

# Create a 3D array of shape (3, 4, 5)
arr = np.arange(3*4*5).reshape(3, 4, 5)

print("Original array shape:", arr.shape)
print("Original array:\n", arr)

# Slice out a subarray: 
# For example, take all elements from:
# - first dimension: index 1 to 2 (inclusive)
# - second dimension: index 1 to 3 (exclusive)
# - third dimension: index 2 to 5 (exclusive)
subarray = arr[1:3, 1:3, 2:5]

print("\nSliced subarray shape:", subarray.shape)
print("Sliced subarray:\n", subarray)


Original array shape: (3, 4, 5)
Original array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

Sliced subarray shape: (2, 2, 3)
Sliced subarray:
 [[[27 28 29]
  [32 33 34]]

 [[47 48 49]
  [52 53 54]]]



---